[build]
  publish = "build/web"

[[redirects]]
  from = "/download/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "/download.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
